# Default values for redis.
# This is a YAML-formatted file.

redisImage:
  repository: redislabs/redis
  tag: 5.0.2-20
  pullPolicy: IfNotPresent

replicas: 3

redisResources:
   limits:
    cpu: 2
    memory: 4096Mi
   requests:
    cpu: 2
    memory: 4096Mi

redisControllerImage:
  repository: redislabs/k8s-controller
  tag: 48_7e5bd8b
  pullPolicy: IfNotPresent

redisControllerConfiguration:
  bdbServiceType: "cluster_ip,headless"
  serviceNaming: "bdb_name"

controllerResources: {}

serviceAccount:
  create: true
  # name: redis-svc

adminUsername: "demo@redislabs.com"
# adminPassword: test123

license: ""

nodeSelector: {}
  # select a specific node pool, for example:
  # cloud.google.com/gke-nodepool: default-pool

persistentVolume:
  enabled: false
  size: 20Gi  # This needs to be *5 the size of redis memory resources
  # storageClass: "-"

externalUIServiceAnnotations: {}

openShiftDeployemnt: false
#imagePullSecrets:
#- name: regsecret

# Override the statefulset name
#statefulsetNameOverride: rediscluster

# For debugging use only, this will allow you to run redis entereprise on a single host.
# This will effectivly might make you'r cluster non HA safe
haSafetyOff: false
