apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "redis-enterprise.fullname" . }}-controller
  labels:
    app: {{ template "redis-enterprise.name" . }}
    chart: {{ template "redis-enterprise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas:
  template:
    metadata:
      labels:
        app: {{ template "redis-enterprise.name" . }}
        chart: {{ template "redis-enterprise.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        redis.io/role: controller
    spec:
      serviceAccountName: {{ template "redis-enterprise.serviceAccountName" . }}
      containers:
      - name: controller
        image: {{ .Values.redisControllerImage.repository }}:{{ .Values.redisControllerImage.tag }}
        imagePullPolicy: {{ .Values.redisControllerImage.pullPolicy }}
        resources:
{{ toYaml .Values.controllerResources | indent 10 }}
        env:
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: REDIS_SERVICE_NAME
            value: {{ template "redis-enterprise.fullname" . }}
          - name: RP_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "redis-enterprise.fullname" . }}
                key: username
          - name: RP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "redis-enterprise.fullname" . }}
                key: password
